swagger: '2.0'
info:
  version: '0.1.0'
  title: 'Inspire download and view services'
  description: 'Specification of download and view services defined by Inspire EU directive'
# Added by API Auto Mocking Plugin
# host: inspireappli.geoapi.fr
# basePath: /
# schemes:
#  - http
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /benoitdavidfr/inspireappli/0.1.0
schemes:
 - https
 - http
paths:
  /:
    get:
      tags:
        - API documentation
      summary: Returns a short description of the API
      operationId: desc
      produces:
        - text/html
        - application/json
      responses:
        '200':
          description: opération réussie
  /doc:
    get:
      tags:
        - API documentation
      summary: Forward to complete documentation site
      operationId: doc
      produces:
        - text/html
      responses:
        '200':
          description: opération réussie
  /spec:
    get:
      tags:
        - API documentation
      summary: Forward to API specification in Swagger
      operationId: spec
      produces:
        - text/html
        - application/json
      responses:
        '200':
          description: opération réussie
  /terms:
    get:
      tags:
        - API documentation
      summary: Returns the terms of use
      operationId: terms
      produces:
        - text/html
      responses:
        '200':
          description: opération réussie
  '/download/{dsid}':
    get:
      tags:
        - download service
      summary: Get Download Service Metadata
      operationId: download
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
      responses:
        '200':
          description: the service metadata
          schema:
            $ref: '#/definitions/downloadCapabilities'
  '/download/{dsid}/describe':
    get:
      tags:
        - download service
      summary: Describe Spatial Data Set
      description: >-
        Returns the description of all the types of Spatial Objects contained in the Spatial Data Set.
      operationId: describe
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
      responses:
        '200':
          description: description of all the types of Spatial Objects 
          schema:
            type: array
            items:
              $ref: '#/definitions/sotDescription'
  '/download/{dsid}/get':
    get:
      tags:
        - download service
      summary: Get Spatial Data Set
      description: >-
        Retrives of a Spatial Data Set.
      operationId: downloadDataset
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
      responses:
        '200':
          description: features of the spatial data set structured with one FeatureCollection per Spatial Object type
          schema:
            type: array
            items:
              type: object
              properties:
                sot:
                  type: string
                featureCollection:
                  $ref: '#/definitions/FeatureCollection'
  '/download/{dsid}/describe/{sot}':
    get:
      tags:
        - download service
      summary: Describe Spatial Object Type
      description: >-
        Returns the description of the specified Spatial Objects types
      operationId: describeSot
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
        - name: sot
          in: path
          description: list of names of the Spatial Object Types
          required: true
          type: array
          items:
            type: string
      responses:
        '200':
          description: description of the specified Spatial Objects types
          schema:
            type: array
            items:
              $ref: '#/definitions/sotDescription'
  '/download/{dsid}/get/{sot}':
    get:
      tags:
        - download service
      summary: Get Spatial Object
      description: >-
        Retrieval of Spatial Objects based upon a query.
      operationId: downloadFeatures
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
        - name: sot
          in: path
          description: list of names of the Spatial Object Types
          required: true
          type: array
          items:
            type: string
      responses:
        '200':
          description: features of the spatial data set structured with one FeatureCollection
          schema:
            $ref: '#/definitions/FeatureCollection'
  '/view/{viewid}':
    get:
      tags:
        - view service
      summary: Get View Service Metadata
      operationId: view
      produces:
        - text/html
        - application/json
      parameters:
        - name: viewid
          in: path
          description: ID of the view service
          required: true
          type: string
      responses:
        '200':
          description: the service metadata
          schema:
            $ref: '#/definitions/viewCapabilities'
  '/view/{viewid}/getMap':
    get:
      tags:
        - view service
      summary: Get Map
      description: >-
        Returns a map containing the geographic and thematic information coming from the available spatial datasets.
        This map is an image spatially referenced
      operationId: getMap
      produces:
        - image/png
      parameters:
        - name: viewid
          in: path
          description: ID of the view service
          required: true
          type: string
        - name: layers
          in: query
          description: list of layer names to be included in the map
          type: array
          items:
            type: string
        - name: styles
          in: query
          description: list of style to be used for each layer
          type: array
          items:
            type: string
        - name: crs
          in: query
          description: Coordinate Reference System of the map
          type: string
        - name: bbox
          in: query
          description: >-
            The 4 corner Coordinate of the two dimensional map for the selected Dimension pair and in the selected
            Coordinate Reference System. The Accept http header is usezd to determine the format of the image.
          type: array
          items:
            type: string
        - name: witdh
          in: query
          description: The map width in pixels
          type: string
        - name: height
          in: query
          description: The map height in pixels
          type: string
      responses:
        '200':
          description: the map
definitions:
  downloadCapabilities:
    type: object
  metadata:
    type: object
    properties:
      title:
        description: >-
          Resource title (1.1)
          A characteristic, and often unique, name by which the resource is known.
          The value domain of this metadata element is free text.
        type: string
      abstract:
        description: >-
          Resource abstract (1.2)
          A brief narrative summary of the content of the resource.
          The value domain of this metadata element is free text.
        type: string
      type:
        enum: [series, dataset, services]
        description: >-
          Resource type (1.3)
          This is the type of resource being described by the metadata.
          The value domain of this metadata element is:
            series: Spatial data set series
            dataset: Spatial data set
            services: Spatial data services
        type: string
      locator:
        description: >-
          Resource locator (1.4)
          The link(s) to the resource and/or the link to additional information about the resource.
          The value domain of this metadata element is a character string, commonly expressed as uniform resource
          locator (URL).
        type: array
        items:
          type: string
      uri:
        description: >-
          Unique resource identifier (1.5)
          A value uniquely identifying the resource.
          The value domain of this metadata element is a mandatory character string code, generally assigned by the
          data owner, and a character string namespace uniquely identifying the context of the identifier code (for
          example, the data owner).
        type: array
        items:
          type: string
  sotDescription:
    type: object
  viewCapabilities:
    type: object
  FeatureCollection:
    type: object
    required:
      - type
      - features
    properties:
      type:
        type: string
        description: the 'FeatureCollection' value
        example: FeatureCollection
      features:
        type: array
        description: list of Features
        items:
          type: object
          required:
            - type
            - properties
            - geometry
          properties:
            type:
              type: string
              description: the 'Feature' value
              example: Feature
            properties:
              type: object
              description: properties of the feature
            geometry:
              type: object
              description: geometry of the feature
externalDocs:
  description: Documentation of the API
  url: https://github.com/benoitdavidfr/geoapi-inspireoai
