swagger: '2.0'
info:
  version: '0.1.0'
  title: 'Inspire download and view services'
  description: >-
    WORK IN PROGRESS
    
    Specification of download and view services defined by 
    [Inspire EU Regulation 976/2009](http://data.europa.eu/eli/reg/2009/976/2014-12-31)
    implementing the [Inspire EU directive](http://data.europa.eu/eli/dir/2007/2/oj).
    
    With the exception of the API documentation and of the dataset URI, each path corresponds to an operation defined
    by the regulation, its summary gives the title of the operation as defined by the regulation and its description
    gives the role of the operation as defined by the regulation followed between parentheses by the reference of the
    operation in the regulation.
    
    For each operation:
      * the requested natural language is defined by the Accept-Language HTTP request header,
      * the natural language used in the response is defined by the Content-Language HTTP response header,
    
# Added by API Auto Mocking Plugin
# host: inspireappli.geoapi.fr
# basePath: /
# schemes:
#  - http
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /benoitdavidfr/inspireinoai/0.1.0
schemes:
 - https
 - http
paths:
  /:
    get:
      tags:
        - API documentation
      summary: Returns a short description of the API
      operationId: desc
      produces:
        - text/html
        - application/json
      responses:
        '200':
          description: opération réussie
  /doc:
    get:
      tags:
        - API documentation
      summary: Forward to complete documentation site
      operationId: doc
      produces:
        - text/html
      responses:
        '200':
          description: opération réussie
  /spec:
    get:
      tags:
        - API documentation
      summary: Forward to API specification in Swagger
      operationId: spec
      produces:
        - text/html
        - application/json
      responses:
        '200':
          description: opération réussie
  /terms:
    get:
      tags:
        - API documentation
      summary: Returns the terms of use
      operationId: terms
      produces:
        - text/html
      responses:
        '200':
          description: opération réussie
  '/{dsid}':
    get:
      tags:
        - dataset URI
      summary: the dataset URI returns the dataset metadata
      description: >-
      operationId: datasetUri
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
      responses:
        '200':
          description: the dataset metadata
          schema:
            $ref: 'https://raw.githubusercontent.com/benoitdavidfr/inspireinoai/master/metadata.yaml#/definitions/metadata'
  '/download/{dsid}':
    get:
      tags:
        - download service
      summary: Get Download Service Metadata
      description: >-
        Provides all necessary information about the service, the available Spatial Data Sets, and describes the service
        capabilities.
        (Annex IV, Part A, Section 2)
      operationId: getDownloadServiceMetadata
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
      responses:
        '200':
          description: the service metadata
          schema:
            $ref: '#/definitions/downloadCapabilities'
  '/download/{dsid}/describe':
    get:
      tags:
        - download service
      summary: Describe Spatial Data Set
      description: >-
        Returns the description of all the types of Spatial Objects contained in the Spatial Data Set.
        (Annex IV, Part A, Section 4)
      operationId: describeSpatialDataSet
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
      responses:
        '200':
          description: description of all the types of Spatial Objects 
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/benoitdavidfr/inspireinoai/master/sotdescription.yaml#/definitions/sotDescription'
  '/download/{dsid}/get':
    get:
      tags:
        - download service
      summary: Get Spatial Data Set
      description: >-
        Retrieves of a Spatial Data Set.
        (Annex IV, Part A, Section 3)
          The only format provided is GeoJSON.
          The only CRS proposed is ETRS89 or equivalent CRS over-seas.
      operationId: getSpatialDataSet
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
      responses:
        '200':
          description: a GeoJSON FeatureCollection with the features of the spatial data set
          schema:
            $ref: '#/definitions/FeatureCollection'
  '/download/{dsid}/describe/{sot}':
    get:
      tags:
        - download service
      summary: Describe Spatial Object Type
      description: >-
        Returns the description of the specified Spatial Objects types
        (Annex IV, Part B, Section 8)
      operationId: describeSpatialObjectType
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
        - name: sot
          in: path
          description: list of names of the Spatial Object Types
          required: true
          type: array
          items:
            type: string
      responses:
        '200':
          description: description of the specified Spatial Objects types
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/benoitdavidfr/inspireinoai/master/sotdescription.yaml#/definitions/sotDescription'
  '/download/{dsid}/get/{sot}':
    get:
      tags:
        - download service
      summary: Get Spatial Object
      description: >-
        Retrieval of Spatial Objects based upon a query.
        (Annex IV, Part B, Section 7)
      operationId: getSpatialObject
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
        - name: sot
          in: path
          description: list of names of the Spatial Object Types
          required: true
          type: array
          items:
            type: string
      responses:
        '200':
          description: a GeoJSON FeatureCollection with the selected features of the spatial data set
          schema:
            $ref: '#/definitions/FeatureCollection'
  '/view/{viewid}':
    get:
      tags:
        - view service
      summary: Get View Service Metadata
      description: >-
        Provides all necessary information about the service and describes service capabilities
        (Annex III, Part A, Section 2)
      operationId: getViewServiceMetadata
      produces:
        - text/html
        - application/json
      parameters:
        - name: viewid
          in: path
          description: ID of the view service
          required: true
          type: string
      responses:
        '200':
          description: the service metadata
          schema:
            $ref: '#/definitions/viewCapabilities'
  '/view/{viewid}/getMap':
    get:
      tags:
        - view service
      summary: Get Map
      description: >-
        Returns a map containing the geographic and thematic information coming from the available spatial datasets.
        This map is an image spatially referenced.
        (Annex III, Part A, Section 3)
          The Accept http header determines the format of the image.
      operationId: getMap
      produces:
        - image/png
      parameters:
        - name: viewid
          in: path
          description: ID of the view service
          required: true
          type: string
        - name: layers
          in: query
          description: list of layer names to be included in the map
          type: array
          items:
            type: string
        - name: styles
          in: query
          description: list of style to be used for each layer
          type: array
          items:
            type: string
        - name: crs
          in: query
          description: Coordinate Reference System of the map
          type: string
        - name: bbox
          in: query
          description: >-
            The 4 corner Coordinate of the two dimensional map for the selected Dimension pair and in the selected
            Coordinate Reference System.
          type: array
          items:
            type: string
        - name: witdh
          in: query
          description: The map width in pixels
          type: string
        - name: height
          in: query
          description: The map height in pixels
          type: string
      responses:
        '200':
          description: the map

definitions:
  downloadCapabilities:
    type: object
    description: >-
      Response of the Get Download Service Metadata request (Annex IV Part A Section 2.2)
    properties:
      serviceMetadata:
        description: >-
          Download Service Metadata (2.2.1.)
          At least contain the INSPIRE metadata elements of the Download Service.
        $ref: 'https://raw.githubusercontent.com/benoitdavidfr/inspireinoai/master/metadata.yaml#/definitions/metadata'
      operationsMetadata:
        description: >-
          Operations Metadata (2.2.2.)
          Provides metadata about the operations implemented by the Download Service. It shall at least provide a
          description of each operation, including as a minimum a description of the data exchanged and the network
          address.
        $ref: 'https://raw.githubusercontent.com/benoitdavidfr/inspireinoai/master/servicecap.yaml#/definitions/operationCap'
      supportedLanguages:
        description: >-
          Supported languages (2.2.3.b)
          The list of the natural languages supported by the Service coded using ISO 639-2 alpha-3.
          
          The response language (2.2.3.a) is given by the Content-Language HTTP response header
        type: array
        items: {type: string}
        example: ['fre','eng']
      datasetMetadata:
        description: >-
          Spatial Data Sets Metadata (2.2.4.)
          The INSPIRE metadata elements of the available Spatial Data Sets shall be provided. In addition,
          for each Spatial Data Set, the list of those Coordinate Reference Systems referred to in Regulation (EU)
          No 1089/2010 which are available shall also be provided.
          
          This property is structured with an array of items, one per available dataset, each one defined by the URI
          of the dataset pointing to its metadata, and the list of available CRS, each one defined by an URI
        type: array
        items:
          description: one item per dataset
          type: object
          properties:
            uri: {type: string}
            crs:
              type: array
              items:
                description: Each item is an URI defining a CRS in which the dataset is available
                type: string

  viewCapabilities:
    type: object
    description: >-
      Response of the Get View Service Metadata request (Annex III Part A Section 2.2)
    properties:
      serviceMetadata:
        description: >-
          View Service Metadata (2.2.1.)
          At least contain the INSPIRE metadata elements of the View Service.
        $ref: 'https://raw.githubusercontent.com/benoitdavidfr/inspireinoai/master/metadata.yaml#/definitions/metadata'
      operationsMetadata:
        description: >-
          Operations Metadata (2.2.2.)
          Describes the operations of the View Service and shall contain as a minimum a description of the data
          exchanged and the network address of each operation.
        $ref: 'https://raw.githubusercontent.com/benoitdavidfr/inspireinoai/master/servicecap.yaml#/definitions/operationCap'
      supportedLanguages:
        description: >-
          Supported languages (2.2.3.b)
          The list of the natural languages supported by the Service coded using ISO 639-2 alpha-3.
          
          The response language (2.2.3.a) is given by the Content-Language HTTP response header
        type: array
        items: {type: string}
        example: ['fre','eng']
      layersMetadata:
        description: >-
          Layers Metadata  (2.2.4.)
        type: array
        items:
          description: one item per layer
          type: object
          properties:
            title:
              description: >-
                Resource Title
                The title of the layer, used for human communication, for presentation of the layer, e.g. in a menu
              type: string
            abstract:
              description: >-
                Resource Abstract
                Layer abstract
              type: string
            keywords:
              description: >-
                Keyword
                Layer Additional keywords
              type: array
              items: {type: string}
            bbox:
              description: >-
                Geographic Bounding Box
                The minimum bounding rectangle in all supported Coordinate Reference Systems of the area covered by the
                layer
              type: array
              items: {type: string}

  FeatureCollection:
    type: object
    required:
      - type
      - features
    properties:
      type:
        type: string
        description: the 'FeatureCollection' value
        example: FeatureCollection
      features:
        type: array
        description: list of Features
        items:
          type: object
          required:
            - type
            - properties
            - geometry
          properties:
            type:
              type: string
              description: the 'Feature' value
              example: Feature
            properties:
              type: object
              description: properties of the feature
            geometry:
              type: object
              description: geometry of the feature

externalDocs:
  description: Documentation of the API
  url: https://github.com/benoitdavidfr/inspireinoai
